### ISSUE TITLE
Plugin dead in Ubuntu 13.10 Saucy

### ISSUE THREAD

**Issue by robgwinprn** [GeditSourceCodePlugin/gedit-source-code-browser#25]
Upgraded to Saucy and this plugin no longer works, can't even enable it. It doesn't show up in the side panel, and in gedit > preferences > plugins I see an error symbol (red circle with line) in place of the checkbox next to Source Code Browser. Tried un/reinstalling both from git and via synaptic and in either case when I restart gedit and pull up the plugin list I see the checkbox but when I click it turns back into the the error symbol. I do have Exuberant Ctags installed, fwiw. Plugin was working just fine up through Ubuntu 13.04.

**Comment by toobaz** [comment]
See #40 , closing
