### ISSUE TITLE
breaks with gedit 3.12

### ISSUE THREAD

**Issue by carandraug** [GeditSourceCodePlugin/gedit-source-code-browser#28]
It seems that with the new version of gedit, this plugin does not work. The tab on the side-panel doesn't even appear. See the [debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746430) for details.

**Comment by zml909** [comment]
yes

**Comment by MinekPo1** [comment]
Of course I have the *one* version that dosen't work.

**Comment by carandraug** [comment]
For what is worth, this is fixed in Debian with the following patch https://sources.debian.org/patches/gedit-source-code-browser-plugin/3.0.3-5.1/0003-Port-to-gedit-3.12.patch/

**Comment by MinekPo1** [comment]
My bad. I have 3.14. It was ctags not being updated...

**Comment by toobaz** [comment]
See #40 , closing
