### ISSUE TITLE
Can not enable plugin in Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by marcohg** [GeditSourceCodePlugin/gedit-source-code-browser#34]
I get this issue:
(gedit:1807): libpeas-WARNING **: 08:11:31.808: The 'python' plugin loader has not been enabled

**Comment by MarcoHG** [comment]
Gedit is 3.28.1

**Comment by ovigia** [comment]
having the same problem on a RHEL 8.4

i can click the about button, it works ok, but the plugin gets a :no_entry_sign: icon

**Comment by toobaz** [comment]
See #40 , closing
