### ISSUE TITLE
Breaks with gedit 3.36.1

### ISSUE THREAD

**Issue by uwekel** [GeditSourceCodePlugin/gedit-source-code-browser#35]
The object model of gedit has obviously changed. In the file "plugin.py" you need to replace the code "document.get_location()" to "document.get_file().get_location()". Then it works again.

**Comment by PJSingh5000** [comment]
I am also experiencing this issue.
However, the work-around above did not work for me.

**Comment by PJSingh5000** [comment]
Here's some more info...

```
$ gedit
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/sourcecodebrowser/plugin.py", line 456, in on_sourcetree_draw
    self._load_active_document_symbols()
  File "/usr/lib/gedit/plugins/sourcecodebrowser/plugin.py", line 401, in _load_active_document_symbols
    location = document.get_location()
AttributeError: 'Document' object has no attribute 'get_location'

```

**Comment by uwekel** [comment]
You still have not replaced the code as explained. See in line 401 and change "document.get_location()" into "document.get_file().get_location()".

**Comment by PJSingh5000** [comment]
I did!
Then I reverted it just to capture the error with the original code, when the change had no effect.

I’ll try making the change again, and capture any errors with the modified code.

**Comment by PJSingh5000** [comment]
uwekel,

Thank you very much. It was very altruistic of you to post this workaround so others could benefit, and you considerately responded to my comment to help guide me.

I reapplied the code change, and it worked. (Previously, perhaps I had forgoten to close all instances of gedit after applying the fix).

        .
        .
        .
        document = self.window.get_active_document()
        if document:
            # location = document.get_location()
            location = document.get_file().get_location()
            if location:
        .
        .
        .

**Comment by kiplingw** [comment]
Thanks @uwekel. It worked.

**Comment by toobaz** [comment]
See #40 , closing
