### ISSUE TITLE
Gedit 40 update

### ISSUE THREAD

**Issue by Supreeeme** [GeditSourceCodePlugin/gedit-source-code-browser#39]
This plugin doesn't seem to be maintained anymore. I've fixed it up for gedit 40 on my fork.
https://github.com/Supreeeme/gedit-source-code-browser

**Comment by ildar** [comment]
ah! nice!
thank you.

**Comment by ildar** [comment]
seems your fork is broken again: clicking on a tag doesn't bring you
to the desired line but complains:
> Traceback (most recent call last):
>  File "/usr/lib64/gedit/plugins/sourcecodebrowser/plugin.py", line 523, in on_tag_activated
>     document.goto_line(line)
> AttributeError: 'Document' object has no attribute 'goto_line'

**Comment by ildar** [comment]
Ah, ok, fixed that:
https://github.com/ildar/gedit-source-code-browser/commits/master

**Comment by Supreeeme** [comment]
I don't actually use gedit anymore, mind if I link to your fork from mine?

**Comment by ildar** [comment]
I get to that just time-to-time so I'd avoid `Maintaned:Yes` but besides
that, yeah, ok.

**Comment by toobaz** [comment]
See #40 , closing
