### ISSUE TITLE
'Document' object has no attribute 'goto_line' (Gedit 44.2)

### ISSUE THREAD

**Issue by PJ-Singh-001** [GeditSourceCodePlugin/gedit-source-code-browser#41]
Gedit Version: 44.2
Distro: Ubuntu 23.04

I experience the following error when clicking on an item in the source code browser panel:

```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/sourcecodebrowser/plugin.py", line 473, in on_tag_activated
    document.goto_line(line)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'goto_line'
```

This probably has something to do [with](https://github.com/GNOME/gedit/blob/0d5002eb869cb7162425902a8599740de8eb9337/NEWS#L4):
> gedit now depends on libgedit-gtksourceview instead of GtkSourceView

**Comment by ildar** [comment]
fix available:
https://github.com/MicahCarrick/gedit-source-code-browser/issues/39#issuecomment-1529733276

**Comment by PJ-Singh-001** [comment]
This did not work for me on Gedit Version 44.2 in Ubuntu 23.10.

Any ideas on what I could do differently?

I tried applying the fix by adding `import gi` to `plugin.py` using the following command...

    sudo sed -i "s|from . import ctags|from . import ctags\nimport gi|g" /usr/lib/gedit/plugins/sourcecodebrowser/plugin.py

...which changes `/usr/lib/gedit/plugins/sourcecodebrowser/plugin.py`...

...from...

    import os
    import sys
    import logging
    import tempfile
    from . import ctags
    from gi.repository import GObject, GdkPixbuf, Gedit, Gtk, PeasGtk, Gio

...to...

    import os
    import sys
    import logging
    import tempfile
    from . import ctags
    import gi
    from gi.repository import GObject, GdkPixbuf, Gedit, Gtk, PeasGtk, Gio

...but I still get the same error.

**Comment by gu-5000** [comment]
No need to import gi.
I have fixed it by replacing:
`
document.goto_line(line)
view.scroll_to_cursor()
`
with

`
it = document.get_iter_at_line(line)
document.place_cursor(it)
view.scroll_to_iter(it, 0.01, True, 0.0, 0.0)
`
I recommend to activate the highlight current line option.

**Comment by gu-5000** [comment]
No need to:
```python 
import gi
```
I have fixed it by replacing:
```python
document.goto_line(line)
view.scroll_to_cursor()
```
with
```python
it = document.get_iter_at_line(line)
document.place_cursor(it)
view.scroll_to_iter(it, 0.01, True, 0.0, 0.0)
```
I recommend to activate the 'highlight current line' option.

**Comment by ildar** [comment]
greetings!
I found a fix that we all have been waiting for:
https://github.com/heguangyu5/gedit-source-code-browser/
thank you, @heguangyu5 !!

**Comment by kiplingw** [comment]
Wonderful @ildar! I'll give it a try, although it doesn't look like it's packaged yet. I'll try and recycle as much of the Ubuntu packaging as possible. Hopefully @heguangyu5 creates a PPA.

**Comment by heguangyu5** [comment]
Wow, surprising! I've used gedit and gedit-source-code-browser for many years, thanks the authors.

However, I'm not familiar with Python language, [the fork](https://github.com/heguangyu5/gedit-source-code-browser/commit/2a3b25d7438c2bf1dd85d4bb95a4a6f1a4702c01) just made it work on ubuntu 24.04/gedit 46.2, it not fully tested.

If it is helpful, someone maybe create a PR to make gedit-source-code-browser better!

**Comment by kiplingw** [comment]
For anyone interested in following progress to get @heguangyu5's fork packaged downstream in Debian to replace the older currently unmaintained fork, you can see my [request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061511) as well as follow the progress of the package [here](https://tracker.debian.org/pkg/gedit-source-code-browser-plugin).

**Comment by toobaz** [comment]
My understanding is that the problem(s) discussed in this issue are solved in current master, which includes @heguangyu5 's edits. So I'm closing it, to coordinate all discussion on the new version in #40 .

Please do open a new bug however if the bug is still there in current master.
